merge class
navgurukul/bhanwari-devi pull request #1035
Opened 2023-08-03 12:13 UTC by saloni-080601

merge class for ACB
New design of class.

2023-08-11 07:38 UTC, komalahire requested changes

2023-08-11 07:38 UTC, komalahire commented on src/components/Class/ClassCard/index.js
> +              )}
Pathway id should not be hard coded.

2023-08-11 07:38 UTC, komalahire commented on src/components/Class/ClassCard/index.js
> +        )}
Pathway id should not be hard coded. here also

2023-08-11 07:38 UTC, komalahire commented on src/components/Class/ClassCard/index.js
> +        >
Add this in CSS file.

2023-08-11 09:18 UTC, jschanker reviewed
Some initial comments

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassCard/index.js
> +          background: timeZone ? "#FFF5CC" : "#FAFAFA",
Reference theme colors here, so if they need to change in the future, we can make the change in one place and be sure that they're the same everywhere across the site.

Also, use `canJoin` instead of `timeZone` to better indicate the variable's meaning.

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassCard/index.js
> +              )}
Is the check for the `pathway_id` in this code temporary? If not, let's add a constant in the constants file with an Array of all `pathway_id`'s for which the `MergeClass` component should be shown. For now, it'd just be `[7]`. Then we can instead do a check like `MERGE_CLASSES.includes(item.pathway_id)` instead of `item.pathway_id === 7`. This allows us to add/remove pathways for which `MergeClass` will be shown by modifying a constant fils without touching this code.

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassCard/index.js
> +        )}
Similar comment here about referring to a constant Array instead of hardcoding the id in the code.

2023-08-11 09:18 UTC, jschanker commented on src/pages/CreateClass/index.js
> +    }).then((res) => {
Probably not a big deal because the response data is small but can we not get this information from the response from `pathway/dropdown` which we had to make anyway?

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassJoinTimerButton/index.js
> +  setTimeZone,
We can make this property more general to be any function we want to run when the user is able to join. Also, it'd be good to rename it something like `onCanJoin` to better reflect its meaning.

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassJoinTimerButton/index.js
> +  });
Without dependencies, this function will run on every render. Not really a problem but it may be better to just move `onCanJoin()` up to line 40 where we're already checking if the user can join. Then we don't need an extra `useEffect`.

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassCard/index.js
> +                setTimeZone={setTimeZone}
With the suggested renames, we'd have:
```suggestion
                onCanJoin={() => setCanJoin(true)}
```

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassCard/index.js
> +  const [timeZone, setTimeZone] = useState(false);
```suggestion
  const [canJoin, setCanJoin] = useState(false);
```

2023-08-11 09:18 UTC, jschanker commented on src/components/Class/ClassList/index.js
> +              set_recurring_classes_data_set(filtered_recurring_classes);
Use `const` instead of `let`. Also, you can define a function with this code, so you don't need to repeat it as you do below on lines 149 - 155.

2023-08-17 13:47 UTC, Poonam-Singh-Bagh commented on src/pages/CreateClass/index.js
>                setNewPathways={setNewPathways}
You're not using `setNewPathways` in `DrawerLeft` component so you can remove it from here.

2023-08-17 13:51 UTC, Poonam-Singh-Bagh commented on src/components/Class/ClassCard/index.js
> +        >
@saloni-080601 you haven't done this yet. Please do it and resolve the conversation once you done.

2023-08-19 15:18 UTC, merged