Partner dashboard
navgurukul/bhanwari-devi pull request #426
Opened 2022-06-03 08:09 UTC by saloni-080601

**Which issue does this refer to ?**
A clear and concise description. Use `#` to refer to github issues and PR

**Brief description of the changes done**
A brief step by step changes made. Example :
1. Upgraded packages
2. Added extra state to handle clicks
3. ...

**People to loop in / review from**
Use `@` key to tag people to review from

2022-06-07 08:53 UTC, Poonam-Singh-Bagh commented
![Screenshot from 2022-06-07 13-24-56](https://user-images.githubusercontent.com/67674096/172338969-aa5aa07c-9fb3-4875-babc-3fd2adaa5246.png)

Icons should be at the bottom even if card content is less then other cards

2022-06-07 08:54 UTC, Poonam-Singh-Bagh commented
![Screenshot from 2022-06-07 13-25-30](https://user-images.githubusercontent.com/67674096/172339272-2415559b-a0bd-4e7b-be06-dd223651898a.png)

![Screenshot from 2022-06-07 13-25-40](https://user-images.githubusercontent.com/67674096/172339298-0bebb749-6053-43fc-a4a0-9976e5c34f1a.png)

Add route link to the Header and Footer as `Our Partner`

2022-06-16 14:22 UTC, Poonam-Singh-Bagh requested changes

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/pages/NewPartner/index.js
> +                            </IconButton>
Icons are not directing to any link

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/pages/NewPartner/index.js
> +                            </IconButton>
Aslo use `<ExternalLink href={partner[item].Url}><PublicIcon variant='outlined' /></ExternalLink>` instead

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/constant.js
>    COURSE_CONTENT: "/course/:courseId",
Why did you add line number 9?

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/components/Dashboard/StudentData/index.js
>            </button>
Make `isDisable` true when click on clear button

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/constant.js
> +  NEW_PARTNER: "/new-partner",
Delete `OurPartner` component and named you component as `OurPartner` and so route. and then you can delete `NEW_PARTNER: "/new-partner",`

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/pages/Login/index.js
>                <Typography
Is there any specific reason to change the container size from sm to md?

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/routing/index.js
> +import NewPartner from "../pages/NewPartner";
Change the name from `import NewPartner from "../pages/NewPartner";` to  `import OurPartner from "../pages/OurPartner";` after renamed you component and delete previous OurPartner component

2022-06-16 14:22 UTC, Poonam-Singh-Bagh commented on src/routing/index.js
> +      <Route exact path={PATHS.NEW_PARTNER} component={NewPartner} />
Same as upper comment from `<Route exact path={PATHS.NEW_PARTNER} component={NewPartner} />` to <Route exact path={PATHS.OUR_PARTNER} component={OurPartner} />

2022-07-01 09:57 UTC, komalahire approved these changes, later dismissed

2022-07-13 08:14 UTC, merged