Fixed Mobile version styling for Meraki team, Volunteer with us, Our …
navgurukul/bhanwari-devi pull request #597
Opened 2022-08-23 13:02 UTC by amansharmma

The styling part for the mobile version of the Meraki team page, Volunteer with us & Our partner is updated here.

2022-08-29 16:14 UTC, Poonam-Singh-Bagh requested changes

2022-08-29 16:14 UTC, Poonam-Singh-Bagh commented on src/components/VolunteerAutomation/index.js
> +                  Typography
Why do you need to use `Typography` attribute. Remove it.

2022-08-29 16:14 UTC, Poonam-Singh-Bagh commented on src/components/VolunteerAutomation/index.js
> +                  Typography
Remove `Typography` attribute

2022-08-29 16:24 UTC, Poonam-Singh-Bagh requested changes

2022-08-29 16:24 UTC, Poonam-Singh-Bagh commented on src/components/VolunteerAutomation/index.js
> +                  Typography
Remove `Typography` attribute

2022-08-29 16:24 UTC, Poonam-Singh-Bagh commented on src/pages/OurPartner/index.js
> +                // Width
Remove it.

2022-09-03 12:26 UTC, amansharmma commented
Added Some more styling and functionality fixes.
Fixed card part of it.
![Screenshot from 2022-09-03 17-50-08](https://user-images.githubusercontent.com/42709018/188270195-a0808af3-aeef-4f2b-a058-38e2232a63df.png)

Text contact area.
![Screenshot from 2022-09-03 17-49-46](https://user-images.githubusercontent.com/42709018/188270207-9eec2341-59d1-4acc-b2c8-cef3cecc0f2a.png)

Card full-width.
![Screenshot from 2022-09-03 17-48-42](https://user-images.githubusercontent.com/42709018/188270216-0f0011d9-e2b8-437a-874d-6831ac400e3d.png)

Removed link & cards for it.
![Screenshot from 2022-09-03 17-48-06](https://user-images.githubusercontent.com/42709018/188270229-827a5ff5-0e17-4b13-a334-cb97fc708e3d.png)

2022-09-05 18:22 UTC, merged